apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: roar-web
  name: roar-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: roar-web
  template:
    metadata:
      labels:
        app: roar-web
    spec:
      containers:
      - image: quay.io/techupskills/roar-web.1.10.1
        imagePullPolicy: Always
        name: roar-web
        ports:
        - containerPort: 8080
          name: web
        livenessProbe:
          httpGet:
             path: /roar/api/v1/status
             port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
      nodeSelector:
        type: mini       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: roar-web
  name: roar-web
spec:
  ports:
  - name: frontend
    port: 8089
    targetPort: 8080
  selector:
    app: roar-web
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: roar-db
  name: mysql
spec:
  replicas: 0
  selector:
    matchLabels:
      app: roar-db
  template:
    metadata:
      labels:
        app: roar-db
        name: mysql
    spec:
      containers:
      - name: mysql
        image: quay.io/techupskills/roar-db:1.0.1
        env:
        - name: MYSQL_DATABASE
          value: registry
        - name: MYSQL_PASSWORD
          value: admin
        - name: MYSQL_ROOT_PASSWORD
          value: root+1
        - name: MYSQL_USER
          value: admin
        imagePullPolicy: Always
        name: mysql
        ports:
        - containerPort: 3306
          name: mysql
        resources:
          limits:
            memory: "100Gi"
            cpu: "1000m"
          requests:
            cpu: "1000m"
            memory: "100Gi"
        readinessProbe:
          exec:
            command:
            - mysql
          failureThreshold: 3
          initialDelaySeconds: 5     
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: roar-db
  name: mysql
spec:
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
  selector:
    name: roar-db

